icons added
eslint/website pull request #783
Opened 2020-09-10 10:36 UTC by Pratyush-Saxena

Icons added ..replacing Text-links in footer

2020-09-11 00:53 UTC, nzakas commented
Thanks for taking a look at this. If you could please take a look at [adding the email you used](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user)  for this commit, we need to get the CLA signature correct.

2020-09-11 00:55 UTC, nzakas commented
This looks like a good first pass. Please take a look at https://deploy-preview-783--eslint.netlify.app/, which previews the site with the change. It looks like the changes are a bit jumbled on mobile. Can you take a look?

2020-09-11 05:07 UTC, Pratyush-Saxena commented
> This looks like a good first pass. Please take a look at https://deploy-preview-783--eslint.netlify.app/, which previews the site with the change. It looks like the changes are a bit jumbled on mobile. Can you take a look?

Well i didn't find anything Jumbeled ....on my mobile
![processed](https://user-images.githubusercontent.com/52444607/92864345-9be49f80-f41a-11ea-83cc-f44d498fedb9.jpeg)
is it that ....Open Js Foundation logo ..you are talking ablout?

2020-09-16 19:01 UTC, nzakas commented
That's what I'm seeing, too. Removing the OpenJS Foundation logo will help. I'd also like to see "Edit this page" either on a separate line from the icons or have the icons aligned to the right of the page to separate them from "Edit this page" (only on mobile, of course)

2020-09-18 07:38 UTC, Pratyush-Saxena commented
> That's what I'm seeing, too. Removing the OpenJS Foundation logo will help. I'd also like to see "Edit this page" either on a separate line from the icons or have the icons aligned to the right of the page to separate them from "Edit this page" (only on mobile, of course)

@nzakas Pls have a look now

2020-09-19 00:20 UTC, nzakas commented
Much better! The only thing we need now is to replace the “OpenJs Foundation” link with the full URL (as we currently have on the site).

And please don’t forget to address the CLA email issue. 

Thanks!

2020-09-19 16:07 UTC, Pratyush-Saxena commented
@nzakas is it all done now....?

2020-09-22 00:50 UTC, nzakas requested changes
Looks good! Just looks like a file was included by accident. We also still need you to electronically sign the CLA.

2020-09-22 00:50 UTC, nzakas commented on .theia/settings.json
> +    "editor.autoSave": "on"
I think this was included by mistake. Can you delete this file?

2020-09-22 04:10 UTC, Pratyush-Saxena reviewed
reviewed

2020-09-22 04:14 UTC, Pratyush-Saxena commented
> Looks good! Just looks like a file was included by accident. We also still need you to electronically sign the CLA.

i have already signed it ....
![cla](https://user-images.githubusercontent.com/52444607/93843660-3a44f080-fcb8-11ea-81ed-dba1b1eef549.png)

2020-09-23 00:58 UTC, nzakas commented
See the original comment: https://github.com/eslint/website/pull/783#issuecomment-690144168

You most likely have a commit that was created using a different email address.

2020-09-24 04:31 UTC, Pratyush-Saxena commented
> See the original comment: [#783 (comment)](https://github.com/eslint/website/pull/783#issuecomment-690144168)
> 
> You most likely have a commit that was created using a different email address.

@nzakas  so what should i do now ...pls tell me in a procedural way..

2020-09-24 20:46 UTC, nzakas commented
See https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user for how to update the email address on your commit. It looks like the first commit in this PR is not linked to your GitHub account. That is the one to fix.

Also, please don't forget to remove `.thea/settings.json` from the PR.

2020-09-25 12:48 UTC, Pratyush-Saxena commented
I think i should creat a new pr ...

2020-09-25 12:48 UTC, closed without merging

2020-09-25 13:20 UTC, Pratyush-Saxena commented
@nzakas  pls head over to #790