Update: What's coming in v8.0.0 blog post
eslint/website pull request #853
Opened 2021-06-11 21:14 UTC by nzakas

This adds some further detail I forgot in the original post.

2021-06-11 21:26 UTC, aladdin-add requested changes
shall we add [`eslint:recommended` updates](https://github.com/eslint/eslint/issues/14673), too?

2021-06-12 00:43 UTC, nzakas commented
Not in this post. This is intended to highlight unusual things to prepare for. We always update eslint:recommended in major releases, so no need for a heads up. We will cover that on the release notes.

2021-06-12 01:19 UTC, aladdin-add approved these changes
LGTM!

2021-06-12 01:25 UTC, snitin315 approved these changes

2021-06-14 17:39 UTC, merged